---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-edge-config
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    server_name : $POD_NAME
    listen : 0.0.0.0:4222
    max_payload : 1Mb
    max_pending : 4Gb
    write_deadline : "2s"
    max_connections : 64K

    jetstream {
      store_dir : "/data/jetstream/store"
      max_mem : 2Gb
      max_file : 10Gb
    }

    leafnodes {
        remotes :[
            {url:"nats://nats-cloud.default.svc.cluster.local:7422",credentials : "/natsCerds/a.creds"} 
        ]
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nats-edge
  labels:
    app: nats-edge
spec:
  selector:
    app: nats-edge
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: leafnodes
    port: 7422
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-edge
  labels:
    app: nats-edge
spec:
  selector:
    matchLabels:
      app: nats-edge
  replicas: 1
  serviceName: "nats-edge"
  template:
    metadata:
      labels:
        app: nats-edge
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: nats-edge-config
      - name: nats-creds
        configMap:
          name: nats-edge-user-a
      - name: pid
        emptyDir: {}
      - name: nats-edge-sts-vol
        emptyDir: {}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: nats
        image: synadia/nats-server:nightly-20210412
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 7422
          name: leafnodes
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        command:
         - "nats-server"
         - "--config"
         - "/etc/nats-config/nats.conf"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats-edge.$(POD_NAMESPACE).svc
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats-config
          - name: nats-creds
            mountPath: /natsCerds
          - name: pid
            mountPath: /var/run/nats
          - name: nats-edge-sts-vol
            mountPath: /data/jetstream
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "/nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60"]
